exports.claimConstants = {
  CLAIM_INTIMATED_BY: 'Claim Intimated By',
  INSURANCE_COMPANY: 'Insurance Company',
  INTIMATOR_DETAILS: 'Intimator Details',
  VERIFICATION_THROUGH: 'Verification Through',
  INTIMATOR_NAME: 'Intimator Name',
  INTIMATOR_CONTACT_NUMBER: 'Intimator Contact Number',
  INTIMATOR_EMAIL_ID: 'Intimator Email Id',
  VERIFY_REGISTERED_MOBILE_NUMBER: 'Verify Registered Mobile Number',
  AUTHENTICATION_REQUIRED: 'Authentication Required',
  POLICY_NUMBER: 'Policy Number',
  NAME_OF_LIFE_ASSURED: 'Name Of Life Assured',
  NAME_OF_PROPOSER: 'Name Of Proposer',
  CLAIM_REPORTING_PERSON_NAME: 'Claim Reporting Person Name',
  CLAIM_TYPE: 'Claim Type',
  CLAIM_REASON: 'Claim Reason',
  DATE_OF_BIRTH_OF_LIFE_ASSURED: 'Date of Birth of Life Assured',
  DATE_OF_EVENT: 'Date of Event',
  CAUSE_OF_EVENT: 'Cause of Event',
  NAME_OF_NOMINEE: 'Name of Nominee',
  NAME_OF_CLAIMANT: 'Name Of Claimant',
  RELATIONSHIP_WITH_LIFE_ASSURED: 'Relationship with Life Assured',
  EMAIL_ID_OF_CLAIMANT: 'Email id of Claimant',
  MOBILE_NO_OF_CLAIMANT: 'Mobile No. Of Claimant',
  ADDRESS_OF_CLAIMANT: 'Address Of Claimant',
  PIN_CODE: 'Pin Code',
  CITY_AREA: 'City/Area',
  DISTRICT: 'District',
  STATE: 'state',
  COUNTRY: 'Country',
  ENTER_OTP: 'Enter otp',
  CLAIM_INTIMATION_DETAILS: 'Claim Intimation Details',
  CLAIM_REGISTRATION: 'Claim Registration',
  ORIGINAL_POLICY_DOCUMENT: 'Original Policy Document',
  DEATH_CERTIFICATE: 'Death Certificate',
  COPY_OF_CANCELLED_CHEQUE_OR_BANK_ACCOUNT_PASSBOOK: 'Copy of cancelled cheque or bank account passbook',
  NOMINEE_CLAIMANT_PHOTO_IDENTITY_ADDRESS_PROOF: "Nominee's/Claimant photo identity & address proof",
  DEATH_IN_HOSPITAL: 'Death in Hospital ?',
  COPY_OF_MEDICAL_RECORDS_ADMISSION_NOTES_DISCHARGE_DEATH_SUMMARY_TEST_REPORTS_ETC:
    'Copy of Medical Records (Admission Notes, Discharge/ Death Summary, Test Reports etc.)',
  ATTENDING_PHYSICIANS_STATEMENT_FORM: 'Attending Physician’s statement (Form)',
  EMPLOYER_CERTIFICATE: 'Employer certificate',
  FIR_OR_PANCHNAMA_POLICE_COMPLAINT: 'FIR or Panchnama / Police complaint',
  POST_MORTEM_REPORT: 'Post Mortem Report',
  FINAL_POLICE_INVESTIGATION_REPORT: 'Final Police Investigation Report (if any)',
  CRITICAL_ILLNESS_CLAIM_FORM: 'Critical illness Claim form',
  ATTESTED_COPIES_OF_MEDICAL_RECORDS_INDOOR_PAPERS_OF_THE_HOSPITAL: 'Attested copies of medical records/ indoor papers of the hospital',
  HOSPITAL_DISCHARGE_SUMMARY: 'Hospital discharge summary',
  HOSPITAL_BILLS: 'Hospital bills',
  DISABILITY_BENEFIT_CLAIM_FORM: 'Disability Benefit Claim form',
  FIRST_INFORMATION_REPORT_FIR_IN_CASE: 'First Information Report (FIR), in case',
  HOSPITAL_AND_SURGICAL_CARE_CLAIM_FORM: 'Hospital and Surgical Care Claim form',
  MATURITY_DISCHARGE_VOUCHER_IN_THE_FORMAT_SHARED_BY_THE_INSURER_ALONG_WITH_INTIMATION:
    'Maturity Discharge Voucher in the format shared by the Insurer along with intimation'
}
