exports.claimConstants = {
  CLAIM_INTIMATED_BY: 'Claim Intimated By',
  INSURANCE_COMPANY: 'Insurance Company',
  INTIMATOR_DETAILS: 'Intimator Details',
  VERIFICATION_THROUGH: 'Verification Through',
  INTIMATOR_NAME: 'Intimator Name',
  INTIMATOR_CONTACT_NUMBER: 'Intimator Contact Number',
  INTIMATOR_EMAIL_ID: 'Intimator Email Id',
  VERIFY_REGISTERED_MOBILE_NUMBER: 'Verify Registered Mobile Number',
  AUTHENTICATION_REQUIRED: 'Authentication Required',
  POLICY_NUMBER: 'Policy Number',
  NAME_OF_LIFE_ASSURED: 'Name Of Life Assured',
  NAME_OF_PROPOSER: 'Name Of Proposer',
  CLAIM_REPORTING_PERSON_NAME: 'Claim Reporting Person Name',
  CLAIM_TYPE: 'Claim Type',
  CLAIM_REASON: 'Claim Reason',
  DATE_OF_BIRTH_OF_LIFE_ASSURED: 'Date of Birth of Life Assured',
  DATE_OF_EVENT: 'Date of Event',
  CAUSE_OF_EVENT: 'Cause of Event',
  NAME_OF_NOMINEE: 'Name of Nominee',
  NAME_OF_CLAIMANT: 'Name Of Claimant',
  RELATIONSHIP_WITH_LIFE_ASSURED: 'Relationship with Life Assured',
  EMAIL_ID_OF_CLAIMANT: 'Email id of Claimant',
  MOBILE_NO_OF_CLAIMANT: 'Mobile No. Of Claimant',
  ADDRESS_OF_CLAIMANT: 'Address Of Claimant',
  PIN_CODE: 'Pin Code',
  CITY_AREA: 'City/Area',
  DISTRICT: 'District',
  STATE: 'state',
  COUNTRY: 'Country',
  ENTER_OTP: 'Enter otp',
  CLAIM_INTIMATION_DETAILS: 'Claim Intimation Details',
  CLAIM_REGISTRATION: 'Claim Registration'
}
